tasks:
  - name: Setup
    command: wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list && sudo apt update && sudo apt install -y mongodb-mongosh && echo "alias MONGO-ATLAS='mongosh "mongodb+srv://nmagee:20oRGqjmo88JOF0k@cluster0.pnxzwgz.mongodb.net/fhy9gs" --apiVersion 1'" > ~/.bashrc && source ~/.bashrc
  - name: Pip Setup
    command: pip install -r requirements.txt